<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\{Apbdes,KontakDesa,Pengumuman,SuratPengajuan,LaporanDarurat,ProdukUmkm,Lowongan,Usulan,Polling,PollingOption,PollingVote,LokasiDesa}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class SmartVillageController extends Controller {
 public function informasi(){return response()->json(['success'=>true,'data'=>['pengumuman'=>Pengumuman::where('aktif',true)->latest('tanggal')->get(),'apbdes'=>Apbdes::where('tahun',now()->year)->get(),'kontak'=>KontakDesa::orderBy('jabatan')->get()]]);}
 public function surat(Request $r){return response()->json(['success'=>true,'data'=>SuratPengajuan::with('user')->when(!$r->user()->isAdmin(),fn($q)=>$q->whereBelongsTo($r->user()))->latest()->paginate(10)]);}
 public function storeSurat(Request $r){abort_if($r->user()->isAdmin(),403);$d=$r->validate(['jenis_surat'=>['required',Rule::in(['sku','sktm','pengantar_rt_rw','pembaruan_kk'])],'keperluan'=>'required|string|max:2000','nomor_telepon'=>'required|string|max:30','dokumen'=>'nullable|file|mimes:pdf,jpg,jpeg,png|max:4096']);$d['dokumen']=$r->file('dokumen')?->store('surat','public');$x=$r->user()->suratPengajuan()->create(['jenis_surat'=>$d['jenis_surat'],'data_pengajuan'=>['keperluan'=>$d['keperluan'],'nomor_telepon'=>$d['nomor_telepon']],'dokumen'=>$d['dokumen']]);return response()->json(['success'=>true,'data'=>$x],201);}
 public function darurat(Request $r){return response()->json(['success'=>true,'data'=>LaporanDarurat::when(!$r->user()->isAdmin(),fn($q)=>$q->whereBelongsTo($r->user()))->latest()->get()]);}
 public function storeDarurat(Request $r){$d=$r->validate(['latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','jenis_darurat'=>'required|string|max:100','nomor_telepon'=>'required|string|max:30']);$d['latitude']=$d['latitude']??0;$d['longitude']=$d['longitude']??0;return response()->json(['success'=>true,'data'=>$r->user()->laporanDarurat()->create($d)],201);}
 public function pasar(){return response()->json(['success'=>true,'data'=>['produk'=>ProdukUmkm::latest()->paginate(12),'lowongan'=>Lowongan::whereDate('tanggal','>=',today())->orderBy('tanggal')->get()]]);}
 public function storePasar(Request $r){abort_if($r->user()->isAdmin(),403);$d=$r->validate(['nama_usaha'=>'required|string|max:255','pemilik'=>'required|string|max:255','kategori'=>'required|string|max:100','nama_produk'=>'required|string|max:255','deskripsi'=>'nullable|string|max:5000','kontak'=>'required|string|max:30']);return response()->json(['success'=>true,'data'=>ProdukUmkm::create([...$d,'user_id'=>$r->user()->id])],201);}
 public function usulan(){return response()->json(['success'=>true,'data'=>Usulan::with('user')->latest()->paginate(12)]);}
 public function storeUsulan(Request $r){$r->merge(['isi'=>$r->input('isi')??$r->input('isi_usulan')]);$d=$r->validate(['judul'=>'required|string|max:255','isi'=>'required|string|max:5000']);$existing=Usulan::where('user_id',$r->user()->id)->where('judul',$d['judul'])->where('isi',$d['isi'])->where('created_at','>=',now()->subMinute())->latest()->first();if($existing)return response()->json(['success'=>true,'data'=>$existing]);return response()->json(['success'=>true,'data'=>$r->user()->usulan()->create($d)],201);}
 public function polling(){return response()->json(['success'=>true,'data'=>Polling::with(['options.votes'])->where('aktif',true)->latest()->get()]);}
 public function votePolling(Request $r,Polling $polling){abort_unless($polling->aktif&&(!$polling->berakhir_pada||$polling->berakhir_pada->isFuture()),422);$d=$r->validate(['polling_option_id'=>'required|integer|exists:polling_option,id']);abort_unless(PollingOption::whereKey($d['polling_option_id'])->where('polling_id',$polling->id)->exists(),422);$v=PollingVote::updateOrCreate(['polling_id'=>$polling->id,'user_id'=>$r->user()->id],['polling_option_id'=>$d['polling_option_id']]);return response()->json(['success'=>true,'data'=>$v]);}
 public function peta(){return response()->json(['success'=>true,'data'=>LokasiDesa::orderBy('kategori')->get()]);}
}
