<x-app-layout>
<x-slot name="header"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="visually-hidden">Dashboard Admin</span><span class="eyebrow">Dashboard Pemerintah Desa</span><h1 class="page-title">Selamat Datang Admin Desa</h1><p class="text-muted mb-0">Berikut ringkasan pelayanan pengaduan masyarakat tahun {{ now()->year }}.</p></div><span class="welcome-date"><i class="fa-regular fa-calendar"></i>{{ now()->translatedFormat('l, d F Y') }}</span></div></x-slot>
<div class="row g-3 mb-4">@foreach([['Jumlah Warga',$jumlahWarga,'fa-users','stat-total'],['Total Laporan',$total,'fa-file-lines','stat-process'],['Surat Masuk',$suratMasuk,'fa-envelope','stat-waiting'],['Darurat Aktif',$daruratAktif,'fa-triangle-exclamation','stat-done']] as [$label,$value,$icon,$class])<div class="col-6 col-xl-3"><div class="card smart-stat {{ $class }} border-0 h-100"><div class="card-body"><span class="smart-stat-icon"><i class="fa-solid {{ $icon }}"></i></span><div><small>{{ $label }}</small><strong>{{ $value }}</strong></div></div></div></div>@endforeach</div>
<div class="d-flex flex-wrap gap-2 mb-4"><a class="btn btn-success" href="{{ route('laporan.index') }}"><i class="fa-solid fa-file-lines me-2"></i>Kelola Laporan</a><a class="btn btn-outline-success" href="{{ route('surat.index') }}"><i class="fa-solid fa-envelope me-2"></i>Surat Masuk</a><a class="btn btn-outline-danger" href="{{ route('admin.smart') }}"><i class="fa-solid fa-triangle-exclamation me-2"></i>Darurat</a><a class="btn btn-outline-primary" href="{{ route('kategori.index') }}"><i class="fa-solid fa-layer-group me-2"></i>Kategori</a></div>
<div class="row g-4 mb-4"><div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h6 fw-bold">Laporan Berdasarkan Status</h2><div class="chart-box"><canvas id="statusChart"></canvas></div></div></div></div><div class="col-lg-8"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h6 fw-bold">Laporan Berdasarkan Kategori</h2><div class="chart-box"><canvas id="categoryChart"></canvas></div></div></div></div><div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6 fw-bold">Tren Laporan Per Bulan</h2><div class="chart-line"><canvas id="monthChart"></canvas></div></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white border-0 p-3 p-md-4"><h2 class="h5 mb-0">Laporan Terbaru</h2></div><div class="table-responsive"><table class="table table-hover align-middle modern-table mb-0"><thead><tr><th>No</th><th>Judul</th><th>Pelapor</th><th>Kategori</th><th>Tanggal</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($latestReports as $laporan)<tr><td>{{ $loop->iteration }}</td><td class="fw-semibold">{{ $laporan->judul }}</td><td>{{ $laporan->user->name }}</td><td>{{ $laporan->kategori->nama }}</td><td class="text-nowrap">{{ $laporan->created_at->format('d M Y') }}</td><td><x-status-badge :status="$laporan->status" /></td><td class="text-nowrap"><a class="btn btn-sm btn-outline-success" href="{{ route('laporan.show',$laporan) }}">Detail</a> <a class="btn btn-sm btn-success" href="{{ route('laporan.edit',$laporan) }}">Ubah Status</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">Belum ada laporan.</td></tr>@endforelse</tbody></table></div></div>
@push('scripts')<script>
const chartColors=['#f59e0b','#2563eb','#16a34a'];
new Chart(document.getElementById('statusChart'),{type:'doughnut',data:{labels:['Menunggu','Diproses','Selesai'],datasets:[{data:@json([$menunggu,$diproses,$selesai]),backgroundColor:chartColors,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});
new Chart(document.getElementById('categoryChart'),{type:'bar',data:{labels:@json($categoryLabels),datasets:[{label:'Jumlah Laporan',data:@json($categoryValues),backgroundColor:'#27855a',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{precision:0}}},plugins:{legend:{display:false}}}});
new Chart(document.getElementById('monthChart'),{type:'line',data:{labels:@json($monthLabels),datasets:[{label:'Jumlah Laporan',data:@json($monthValues),borderColor:'#176b45',backgroundColor:'rgba(23,107,69,.12)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});
</script>@endpush
</x-app-layout>
