<x-app-layout><x-slot name="header"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3"><div><a class="back-link" href="{{ route('laporan.index') }}"><i class="fa-solid fa-arrow-left"></i> Kembali ke daftar</a><h1 class="page-title mt-3">Detail Laporan</h1></div><div class="d-flex gap-2"><a class="btn btn-village" href="{{ route('laporan.edit',$laporan) }}"><i class="fa-solid fa-pen me-2"></i>{{ auth()->user()->isAdmin() ? 'Ubah Status' : 'Edit Laporan' }}</a><form method="POST" action="{{ route('laporan.destroy',$laporan) }}" onsubmit="return confirm('Yakin ingin menghapus laporan ini? Data dan foto laporan tidak dapat dikembalikan.')">@csrf @method('DELETE')<button class="btn btn-outline-danger"><i class="fa-regular fa-trash-can me-2"></i>Hapus</button></form></div></div></x-slot>
<div class="card report-detail-card border-0 fade-up"><div class="row g-0"><div class="col-lg-7 report-media">@if($laporan->foto && file_exists(public_path($laporan->foto)))<img src="{{ url($laporan->foto) }}" alt="Foto laporan" class="img-fluid rounded" style="width:100%;height:400px;object-fit:cover;">@elseif($laporan->foto)<div class="report-placeholder"><i class="fa-regular fa-image"></i><span>File foto tidak ditemukan</span></div>@else<div class="report-placeholder"><i class="fa-regular fa-image"></i><span>Tidak ada foto pendukung</span></div>@endif</div><div class="col-lg-5"><div class="report-summary"><div class="d-flex justify-content-between align-items-start gap-3"><span class="category-pill"><i class="fa-solid fa-layer-group"></i>{{ $laporan->kategori->nama }}</span><x-status-badge :status="$laporan->status" /></div><h2>{{ $laporan->judul }}</h2><p class="report-content">{{ $laporan->isi_laporan }}</p><div class="report-meta"><div><span class="meta-icon"><i class="fa-regular fa-user"></i></span><span><small>Pelapor</small><strong>{{ $laporan->user->name }}</strong></span></div><div><span class="meta-icon blue"><i class="fa-regular fa-calendar"></i></span><span><small>Tanggal laporan</small><strong>{{ $laporan->created_at->format('d M Y, H:i') }}</strong></span></div></div></div></div></div></div>
@php
    $steps = ['menunggu' => 1, 'diproses' => 2, 'selesai' => 3];
    $currentStep = $steps[$laporan->status] ?? 1;
@endphp
<div class="card timeline-card border-0 mt-4"><div class="card-body p-4 p-lg-5"><div class="content-title"><h2>Perjalanan Laporan</h2><p>Pantau perkembangan tindak lanjut laporan.</p></div><div class="status-timeline">@foreach([['Laporan dibuat','Laporan telah diterima sistem','fa-file-circle-check'],['Sedang diproses','Petugas menindaklanjuti laporan','fa-gears'],['Selesai','Permasalahan telah diselesaikan','fa-circle-check']] as $i=>[$title,$desc,$icon])<div class="timeline-step {{ $currentStep >= $i+1 ? 'active' : '' }}"><span><i class="fa-solid {{ $icon }}"></i></span><div><strong>{{ $title }}</strong><small>{{ $desc }}</small></div></div>@endforeach</div></div></div>
<section class="mt-4"><div class="content-title mb-3"><h2>Tanggapan Petugas</h2><p>Informasi tindak lanjut dari pemerintah desa.</p></div>@forelse($laporan->tanggapan as $tanggapan)<div class="response-modern"><span class="response-avatar"><i class="fa-solid fa-user-shield"></i></span><div><div class="d-flex flex-wrap justify-content-between gap-2"><strong>{{ $tanggapan->user->name }}</strong><time>{{ $tanggapan->created_at->diffForHumans() }}</time></div><p>{{ $tanggapan->isi }}</p></div></div>@empty<div class="empty-response"><i class="fa-regular fa-comments"></i><div><strong>Belum ada tanggapan</strong><span>Petugas akan memberikan informasi setelah laporan diperiksa.</span></div></div>@endforelse
@if(auth()->user()->isAdmin())<div class="card form-modern border-0 mt-4"><div class="card-body p-4"><h3 class="h5 fw-bold">Berikan Tanggapan</h3><form method="POST" action="{{ route('tanggapan.store') }}">@csrf<input type="hidden" name="laporan_id" value="{{ $laporan->id }}"><textarea class="form-control @error('isi_tanggapan') is-invalid @enderror" name="isi_tanggapan" rows="4" placeholder="Tulis informasi tindak lanjut..." required>{{ old('isi_tanggapan') }}</textarea>@error('isi_tanggapan')<div class="invalid-feedback">{{ $message }}</div>@enderror<button class="btn btn-village mt-3"><i class="fa-regular fa-paper-plane me-2"></i>Kirim Tanggapan</button></form></div></div>@endif</section>
</x-app-layout>
