<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Admin') · LaporDesa</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="admin-body"><div class="page-loader" id="pageLoader"><div class="spinner-border text-success"></div></div>
<nav class="navbar navbar-dark village-navbar fixed-top admin-navbar shadow-sm">
    <div class="container-fluid"><button class="btn text-white d-lg-none" data-bs-toggle="offcanvas" data-bs-target="#adminSidebar"><i class="fa-solid fa-bars"></i></button><a class="navbar-brand fw-bold" href="{{ route('admin.dashboard') }}">LaporDesa Admin</a>
        <div class="dropdown ms-auto"><button class="btn btn-link text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"><i class="fa-solid fa-bell me-1"></i><span class="badge text-bg-danger">{{ auth()->user()->unreadNotifications()->count() }}</span></button><div class="dropdown-menu dropdown-menu-end notification-menu">@forelse(auth()->user()->notifications()->latest()->limit(6)->get() as $notification)<a class="dropdown-item py-2 {{ $notification->read_at ? '' : 'fw-semibold' }}" href="{{ route('notifications.read', $notification) }}"><small class="d-block text-success">{{ $notification->data['title'] }}</small><span class="small">{{ $notification->data['message'] }}</span></a>@empty<span class="dropdown-item-text text-muted">Belum ada notifikasi.</span>@endforelse</div></div>
        <form method="POST" action="{{ route('logout') }}" class="ms-2">@csrf<button class="btn btn-outline-light btn-sm"><i class="fa-solid fa-right-from-bracket"></i> Keluar</button></form>
    </div>
</nav>
<aside class="offcanvas-lg offcanvas-start admin-sidebar" tabindex="-1" id="adminSidebar"><div class="offcanvas-header"><h5>Menu Admin</h5><button class="btn-close btn-close-white" data-bs-dismiss="offcanvas"></button></div><div class="offcanvas-body d-block p-3"><a class="admin-brand" href="{{ route('admin.dashboard') }}"><span><i class="fa-solid fa-landmark"></i></span>Lapor<b>Desa</b></a><div class="admin-profile mb-4"><div class="avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div><div><strong>{{ auth()->user()->name }}</strong><small>Administrator Desa</small></div></div><nav class="nav flex-column gap-1"><a class="nav-link active" href="{{ route('admin.dashboard') }}"><i class="fa-solid fa-chart-pie"></i> Dashboard</a><a class="nav-link" href="#"><i class="fa-solid fa-users"></i> Kelola Warga</a><a class="nav-link" href="{{ route('laporan.index') }}"><i class="fa-solid fa-file-lines"></i> Laporan Masuk</a><a class="nav-link" href="{{ route('surat.index') }}"><i class="fa-solid fa-envelope"></i> Surat Online</a><a class="nav-link" href="{{ route('informasi.index') }}"><i class="fa-solid fa-chart-column"></i> APBDes</a><a class="nav-link" href="{{ route('pasar.index') }}"><i class="fa-solid fa-store"></i> UMKM</a><a class="nav-link" href="{{ route('usulan.index') }}"><i class="fa-solid fa-lightbulb"></i> Usulan</a><a class="nav-link" href="{{ route('polling.index') }}"><i class="fa-solid fa-square-poll-vertical"></i> Polling</a><a class="nav-link" href="{{ route('peta.index') }}"><i class="fa-solid fa-map"></i> Peta Desa</a><a class="nav-link" href="{{ route('profile.edit') }}"><i class="fa-solid fa-gear"></i> Pengaturan</a></nav></div></aside>
<main class="admin-content"><div class="container-fluid p-3 p-md-4 p-xl-5">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @yield('content')</div></main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.9/dist/chart.umd.min.js"></script>@stack('scripts')
</body></html>
