<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>LaporDesa · Smart Village</title><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-slate-50 text-slate-800" x-data="{sidebar:false}"><div class="page-loader" id="pageLoader"><div class="spinner-border text-success"></div></div>
<div x-show="sidebar" x-transition.opacity class="fixed inset-0 z-40 bg-slate-950/50 lg:hidden" @click="sidebar=false"></div>
<aside :class="sidebar?'translate-x-0':'-translate-x-full'" class="fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-gradient-to-b from-emerald-950 via-emerald-900 to-teal-900 p-5 text-white shadow-2xl transition-transform lg:translate-x-0">
<a href="{{ auth()->user()->isAdmin()?route('admin.dashboard'):route('dashboard') }}" class="mb-7 flex items-center gap-3 px-2 text-xl font-bold text-white"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-white/15"><i class="fa-solid fa-landmark"></i></span>Lapor<span class="text-emerald-300">Desa</span></a>
<div class="mb-5 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-3"><span class="grid h-11 w-11 place-items-center rounded-xl bg-emerald-400/20 font-extrabold">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><div class="min-w-0"><strong class="block truncate text-sm">{{ auth()->user()->name }}</strong><small class="text-emerald-200">{{ auth()->user()->isAdmin()?'Admin Desa':'Warga Desa' }}</small></div></div>
<nav class="flex-1 space-y-1 overflow-y-auto pr-1"><x-sidebar-link :href="auth()->user()->isAdmin()?route('admin.dashboard'):route('dashboard')" icon="fa-chart-pie" :active="request()->routeIs('dashboard','admin.dashboard')">Dashboard</x-sidebar-link>@unless(auth()->user()->isAdmin())<x-sidebar-link :href="route('laporan.create')" icon="fa-pen-to-square" :active="request()->routeIs('laporan.create')">Buat Laporan</x-sidebar-link>@endunless<x-sidebar-link :href="route('laporan.index')" icon="fa-clock-rotate-left" :active="request()->routeIs('laporan.index', 'laporan.show', 'laporan.edit')">{{ auth()->user()->isAdmin()?'Laporan Masuk':'Riwayat Laporan' }}</x-sidebar-link><x-sidebar-link :href="route('surat.index')" icon="fa-envelope-open-text" :active="request()->routeIs('surat.*')">Surat Online</x-sidebar-link><x-sidebar-link :href="route('informasi.index')" icon="fa-circle-info" :active="request()->routeIs('informasi.*')">Informasi Desa</x-sidebar-link><x-sidebar-link :href="route('darurat.index')" icon="fa-triangle-exclamation" :active="request()->routeIs('darurat.*')">Panic Button</x-sidebar-link><x-sidebar-link :href="route('pasar.index')" icon="fa-store" :active="request()->routeIs('pasar.*')">Pasar Desa</x-sidebar-link><x-sidebar-link :href="route('usulan.index')" icon="fa-lightbulb" :active="request()->routeIs('usulan.*')">Usulan Warga</x-sidebar-link><x-sidebar-link :href="route('polling.index')" icon="fa-square-poll-vertical" :active="request()->routeIs('polling.*')">Polling</x-sidebar-link><x-sidebar-link :href="route('peta.index')" icon="fa-map-location-dot" :active="request()->routeIs('peta.*')">Peta Desa</x-sidebar-link><x-sidebar-link :href="route('profile.edit')" icon="fa-user" :active="request()->routeIs('profile.*')">Profil</x-sidebar-link></nav>
<form method="POST" action="{{ route('logout') }}" class="mt-4">@csrf<button class="flex w-full items-center justify-center gap-2 rounded-xl border border-white/20 px-4 py-3 text-sm font-bold text-white hover:bg-white/10"><i class="fa-solid fa-arrow-right-from-bracket"></i>KELUAR</button></form></aside>
<div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-8"><button class="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 lg:hidden" @click="sidebar=true"><i class="fa-solid fa-bars"></i></button><div class="hidden md:block"><span class="text-xs font-bold uppercase tracking-widest text-emerald-600">Smart Village Digital</span><p class="m-0 text-sm text-slate-500">Pelayanan publik dalam satu platform</p></div><div class="dropdown ms-auto"><button class="relative grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white" data-bs-toggle="dropdown"><i class="fa-regular fa-bell"></i>@if(auth()->user()->unreadNotifications()->count())<span class="absolute -right-1 -top-1 rounded-full bg-red-500 px-1.5 text-[10px] text-white">{{ auth()->user()->unreadNotifications()->count() }}</span>@endif</button><div class="dropdown-menu dropdown-menu-end notification-menu border-0 shadow-lg">@forelse(auth()->user()->notifications()->latest()->limit(5)->get() as $notification)<a class="dropdown-item py-2" href="{{ route('notifications.read',$notification) }}"><strong class="block text-xs">{{ $notification->data['title'] }}</strong><small>{{ $notification->data['message'] }}</small></a>@empty<span class="dropdown-item-text text-muted">Belum ada notifikasi</span>@endforelse</div></div></header>
<main class="p-4 md:p-8">@isset($header)<div class="mb-7">{{ $header }}</div>@endisset @if(session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif {{ $slot }}</main></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.9/dist/chart.umd.min.js"></script>@stack('scripts')</body></html>
